background_opacity 0.0
background #000000
foreground #ffffff
font_family JetBrainsMono Nerd Font
font_size 11.0
hide_window_decorations yes
confirm_os_window_close 0
placement_strategy center
scrollback_lines 0
cursor_blink_interval 0
window_padding_width 0
draw_minimal_borders yes
initial_window_width 1440
initial_window_height 120